### PR TITLE
Eslint-ing

### LINKED ISSUE #110: eslint this stuff
we should add some basic eslinting etc and think about running it for travis (maybe only as an advisory non failing output unless we ignore styling errors)

### PR DESCRIPTION
**Pull request by sandfox**
A first attempt at linting
fixes #110

### CODE REVIEW

File: lib/generic-pool.js [hunk 1]
```diff
@@ -2,78 +2,76 @@
...
+}
 
-PriorityQueue.prototype.enqueue = function enqueue(obj, priority) {
-  var priorityOrig;
+PriorityQueue.prototype.enqueue = function enqueue (obj, priority) {
+  var priorityOrig
 
   // Convert to integer with a default value of 0.
-  priority = priority && + priority | 0 || 0;
+  priority = priority && + priority | 0 || 0 // eslint-disable-line space-unary-ops
```
Comment (felixfbecker) [inline lib/generic-pool.js]: why this?

**Comment by felixfbecker** [comment]
I think the code is now in a much better state than before. :+1:

File: lib/generic-pool.js (hunk 1 above)
Comment (sandfox) [inline lib/generic-pool.js]: Because I'm not entirely sure quite how this resolves and operator precedence and didn't know how to make it less opaque at the time, it seems like an overly clever way of achieving it's a goal. So I just bailed and disabled the checking :-p 

Any input / improvements / explanation gladly excepted!

Comment (felixfbecker) [inline lib/generic-pool.js]: Why do you convert? The class is totally internal, so it should be safe that priority is always an int. I also dont get the default value - if you convert it to an int, the only case where the right hand side of the `||` gets evaluated is when the left hand side is already zero.

**Comment by felixfbecker** [comment]
You should also update the examples in the readme to standard style.

**Comment by sandfox** [comment]
Ah yes, I think I might do that as part of #117 - where I basically plan to put most of the codeblocks into an examples folder so they can get linted and somehow (probably manually to start with) sync them up with the copies in the README.

File: lib/generic-pool.js (hunk 1 above)
Comment (sandfox) [inline lib/generic-pool.js]: The conversion happens because `pool.acquire` directly passes through any priority value so it's some external  user supplied value or `undefined`. Removing the last `|| 0` means if priority is `undefined` then it will stay as `undefined` after that block. I'm just going to fix the error and remove the eslint-disable line for now
